name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      # Build and run unit tests
      - name: Build and Test Application
        run: |
          cd internal/application
          go build
          go test ./... -coverprofile=coverage.out
          
            # Build and run unit tests

      - name: Build and Test Domain
        run: |
          cd internal/domain
          go build
          go test ./... -coverprofile=coverage.out

      - name: Build and Test Persistence
        run: |
          cd internal/infrastructure/persistence
          go build
          go test ./... -coverprofile=coverage.out

